//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Capa1PresentacionWeb.CapaWCF {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IService", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AgregarOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModificarOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::Capa1PresentacionWeb.Properties.Settings.Default.Capa1PresentacionWeb_CapaWCF_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AgregarCompletedEventHandler AgregarCompleted;
        
        /// <remarks/>
        public event ModificarCompletedEventHandler ModificarCompleted;
        
        /// <remarks/>
        public event ConsultarCompletedEventHandler ConsultarCompleted;
        
        /// <remarks/>
        public event EliminarCompletedEventHandler EliminarCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService/Agregar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Agregar([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] UsuarioModel usario, out bool AgregarResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool AgregarResultSpecified) {
            object[] results = this.Invoke("Agregar", new object[] {
                        usario});
            AgregarResult = ((bool)(results[0]));
            AgregarResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void AgregarAsync(UsuarioModel usario) {
            this.AgregarAsync(usario, null);
        }
        
        /// <remarks/>
        public void AgregarAsync(UsuarioModel usario, object userState) {
            if ((this.AgregarOperationCompleted == null)) {
                this.AgregarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregarOperationCompleted);
            }
            this.InvokeAsync("Agregar", new object[] {
                        usario}, this.AgregarOperationCompleted, userState);
        }
        
        private void OnAgregarOperationCompleted(object arg) {
            if ((this.AgregarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgregarCompleted(this, new AgregarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService/Modificar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Modificar([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] UsuarioModel usario, out bool ModificarResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool ModificarResultSpecified) {
            object[] results = this.Invoke("Modificar", new object[] {
                        usario});
            ModificarResult = ((bool)(results[0]));
            ModificarResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void ModificarAsync(UsuarioModel usario) {
            this.ModificarAsync(usario, null);
        }
        
        /// <remarks/>
        public void ModificarAsync(UsuarioModel usario, object userState) {
            if ((this.ModificarOperationCompleted == null)) {
                this.ModificarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModificarOperationCompleted);
            }
            this.InvokeAsync("Modificar", new object[] {
                        usario}, this.ModificarOperationCompleted, userState);
        }
        
        private void OnModificarOperationCompleted(object arg) {
            if ((this.ModificarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModificarCompleted(this, new ModificarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService/Consultar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
        public UsuarioModel[] Consultar() {
            object[] results = this.Invoke("Consultar", new object[0]);
            return ((UsuarioModel[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarAsync() {
            this.ConsultarAsync(null);
        }
        
        /// <remarks/>
        public void ConsultarAsync(object userState) {
            if ((this.ConsultarOperationCompleted == null)) {
                this.ConsultarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarOperationCompleted);
            }
            this.InvokeAsync("Consultar", new object[0], this.ConsultarOperationCompleted, userState);
        }
        
        private void OnConsultarOperationCompleted(object arg) {
            if ((this.ConsultarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarCompleted(this, new ConsultarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService/Eliminar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Eliminar(int idUsario, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idUsarioSpecified, out bool EliminarResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool EliminarResultSpecified) {
            object[] results = this.Invoke("Eliminar", new object[] {
                        idUsario,
                        idUsarioSpecified});
            EliminarResult = ((bool)(results[0]));
            EliminarResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void EliminarAsync(int idUsario, bool idUsarioSpecified) {
            this.EliminarAsync(idUsario, idUsarioSpecified, null);
        }
        
        /// <remarks/>
        public void EliminarAsync(int idUsario, bool idUsarioSpecified, object userState) {
            if ((this.EliminarOperationCompleted == null)) {
                this.EliminarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarOperationCompleted);
            }
            this.InvokeAsync("Eliminar", new object[] {
                        idUsario,
                        idUsarioSpecified}, this.EliminarOperationCompleted, userState);
        }
        
        private void OnEliminarOperationCompleted(object arg) {
            if ((this.EliminarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarCompleted(this, new EliminarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class UsuarioModel {
        
        private string sexoUsuarioField;
        
        private System.DateTime fechaNacimientoUsuarioField;
        
        private bool fechaNacimientoUsuarioFieldSpecified;
        
        private decimal idUsuarioField;
        
        private bool idUsuarioFieldSpecified;
        
        private string nombreUsuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SexoUsuario {
            get {
                return this.sexoUsuarioField;
            }
            set {
                this.sexoUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime fechaNacimientoUsuario {
            get {
                return this.fechaNacimientoUsuarioField;
            }
            set {
                this.fechaNacimientoUsuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaNacimientoUsuarioSpecified {
            get {
                return this.fechaNacimientoUsuarioFieldSpecified;
            }
            set {
                this.fechaNacimientoUsuarioFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idUsuarioSpecified {
            get {
                return this.idUsuarioFieldSpecified;
            }
            set {
                this.idUsuarioFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string nombreUsuario {
            get {
                return this.nombreUsuarioField;
            }
            set {
                this.nombreUsuarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AgregarCompletedEventHandler(object sender, AgregarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AgregarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AgregarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool AgregarResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool AgregarResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ModificarCompletedEventHandler(object sender, ModificarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ModificarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ModificarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool ModificarResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool ModificarResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ConsultarCompletedEventHandler(object sender, ConsultarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UsuarioModel[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UsuarioModel[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void EliminarCompletedEventHandler(object sender, EliminarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EliminarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EliminarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool EliminarResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool EliminarResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591